Collection section
HighlanderRobotics/lovat-website pull request #20
Opened 2024-04-07 22:02 UTC by oliviasully

Make the collection section for the home page.

2024-04-08 21:18 UTC, MangoSwirl requested changes

2024-04-08 21:18 UTC, MangoSwirl commented on src/lib/CollectionSection.svelte
Indentation in this file seems a bit inconsistent. Have you run prettier?

2024-04-08 21:18 UTC, MangoSwirl commented on src/lib/CollectionSection.svelte
> +				alt="Screenshot of collection app."
We never call Lovat Collection "collection app." And maybe be a bit more descriptive about the specific page pictured?

2024-04-08 21:18 UTC, MangoSwirl commented on src/lib/Statistics.svelte
> +			<p>of tournaments scouted</p>
We don't have data on tournaments from previous years, so it would be more accurate to say "of 2024 tournaments scouted"

2024-04-09 00:08 UTC, CassieColby requested changes
Looks good to me for the most part. Once you make Collins changes it should be ready to publish. Awesome work!

2024-04-14 04:15 UTC, MangoSwirl commented
You can ignore the Vercel deployment failing, just added it to the repo to experiment with differences in load times.

2024-05-02 23:51 UTC, MangoSwirl approved these changes
Looks great!

2024-05-02 23:52 UTC, CassieColby reviewed
Looks good!

2024-05-03 00:58 UTC, merged